# Generated by Django 2.0.2 on 2018-10-27 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admins_app', '0001_initial'),
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('detail_address', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=5)),
                ('telephone', models.CharField(max_length=20)),
                ('cellphone', models.CharField(max_length=11)),
                ('users', models.ForeignKey(db_column='user_idd', on_delete=django.db.models.deletion.CASCADE, to='admins_app.User')),
            ],
            options={
                'db_table': 't_address',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('order_uuid', models.CharField(max_length=20)),
                ('status', models.BooleanField()),
                ('address', models.ForeignKey(db_column='order_addid', on_delete=django.db.models.deletion.CASCADE, to='shopping_app.Address')),
                ('user', models.ForeignKey(db_column='order_uid', on_delete=django.db.models.deletion.CASCADE, to='admins_app.User')),
            ],
            options={
                'db_table': 't_order',
            },
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('book', models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.CASCADE, to='home_page.Books')),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='shopping_app.Order')),
            ],
            options={
                'db_table': 't_user_order',
            },
        ),
    ]
