# Generated by Django 2.0.2 on 2018-10-27 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('book_publish', models.CharField(max_length=20)),
                ('publish_time', models.DateTimeField()),
                ('revision', models.IntegerField()),
                ('isbn', models.IntegerField(db_column='ISBN')),
                ('word_count', models.IntegerField()),
                ('page_number', models.IntegerField()),
                ('open_type', models.CharField(max_length=20)),
                ('paper', models.CharField(max_length=20)),
                ('package', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dang_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('editor_recommend', models.BooleanField()),
                ('content_introduce', models.CharField(max_length=2000)),
                ('author_introduce', models.CharField(max_length=2000)),
                ('menu', models.CharField(max_length=2000)),
                ('media_review', models.IntegerField()),
                ('digest_image_path', models.FileField(upload_to='pic1')),
                ('produce_image_path', models.FileField(upload_to='pic2')),
                ('printing_time', models.DateTimeField()),
                ('stock', models.IntegerField()),
                ('shelves_date', models.DateTimeField()),
                ('customer_score', models.IntegerField()),
                ('book_status', models.BooleanField()),
                ('sales', models.IntegerField()),
            ],
            options={
                'db_table': 't_books',
            },
        ),
        migrations.CreateModel(
            name='FirstCategory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('parent_category', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 't_first',
            },
        ),
        migrations.CreateModel(
            name='SecondCategory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('child_category', models.CharField(max_length=20)),
                ('first', models.ForeignKey(db_column='first_cate_id', on_delete=django.db.models.deletion.CASCADE, to='home_page.FirstCategory')),
            ],
            options={
                'db_table': 't_second',
            },
        ),
        migrations.AddField(
            model_name='books',
            name='second',
            field=models.ForeignKey(db_column='second_cate_id', on_delete=django.db.models.deletion.CASCADE, to='home_page.SecondCategory'),
        ),
    ]
